/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_resoft_ResoftVoice */

#ifndef _Included_com_resoft_ResoftVoice
#define _Included_com_resoft_ResoftVoice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_resoft_ResoftVoice
 * Method:    resoftJniCall
 * Signature: (Lcom/resoft/InputParam;Lcom/resoft/OutputResult;)I
 */
JNIEXPORT jint JNICALL Java_com_resoft_ResoftVoice_resoftJniCall
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif
